plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ./README.md
  - ./git.md
  - ./markdown.md
  - ./visual-studio.md
title: [Cheatsheets]
show_download: [false]