plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/midnight@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - md/git.md
  - md/markdown.md
  - md/visual-studio.md
title: [Cheatsheets]
show_download: [false]